baseURL = 'https://r9s.dev/'
languageCode = 'en-us'
title = 'r9s.dev - Markus Rothlübbers'
theme = 'PaperMod'
defaultTheme = 'auto'

[params]
description = "Hi, I'm Markus — software engineer. Find me on GitHub, LinkedIn, and Strava."
author = "Markus Rothlübbers"

[params.profileMode]
enabled = true
title = 'Moin 👋'

[params.schema]
publisherType = "Person"

[[params.socialIcons]]
name = "github"
url = "https://github.com/klitztuch"

[[params.socialIcons]]
name = "keybase"
url = "https://keybase.io/klitztuch"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/markus-rothl%C3%BCbbers-58420b18b/"

[[params.socialIcons]]
name = "strava"
url = "https://www.strava.com/athletes/klitztuch"
